### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by actionless** [protesilaos/tempus-themes#3]
Appreciate your work!
I've imported your colorschemes to another GPL3 application called Oomox:
https://github.com/actionless/oomox/commit/6cc361a7deeebaa82f88bd8d2f3b2af69696bc8c

Since It's used ofr accessibility-oriented purposes (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=865621) i found what it could be useful to ship few WCAG AA compliant color palettes.

**Comment by protesilaos** [comment]
Excellent! Included an Oomox reference in the README, under the section [external project integrations](https://github.com/protesilaos/tempus-themes#external-project-integrations).

**Comment by actionless** [comment]
thanks!
